name: CI - Bot Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências (se houver)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verificar HTML
        run: |
          sudo apt-get install tidy -y
          tidy -qe ./pages/*.html || true

      - name: Verificar Sintaxe Python
        run: |
          if ls *.py 1> /dev/null 2>&1; then python -m py_compile *.py; fi

      - name: Relatório final
        run: echo "✅ Build concluído com sucesso!"
