services:
  bot-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./screenshots:/app/screenshots
    environment:
      - DATABASE_PATH=/app/data/bot_database.db
    restart: unless-stopped

  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle_db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: sua_senha
    restart: unless-stopped

volumes:
  bot_data:
  bot_screenshots:
